// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "heroFrontAttack4":return img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffefefeefff..........
..ffe22f222eef..........
..fe2ffffff2ef..........
..fffffeefffff......ccc.
.ffefbffffbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
